/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).  The Bosch IoT Things HTTP API uses response status codes     (see [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6))     to indicate whether a specific request has been successfully completed, or not. However, the descriptions we provide additionally to the status code (e.g. in our API docs, or error codes like. \"solutions:transaction.count.exceeded\") might change without advance notice. These are not be considered as official API, and must therefore not be applied in your applications or tests.
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotthings
// Solution struct for Solution
type Solution struct {
	// Unique identifier representing a specific Solution
	SolutionId string `json:"solutionId"`
	// A token to identify requests of users associated with the solution
	ApiToken string `json:"apiToken"`
	Plan PlanType `json:"plan"`
	PlanObject SolutionPlanObject `json:"planObject"`
	// The name of the service
	ServiceName string `json:"serviceName"`
	Status SolutionStatus `json:"status"`
	Customer SolutionCustomer `json:"customer"`
	Namespaces Namespaces `json:"namespaces,omitempty"`
	EffectiveUsageLimits UsageLimits `json:"effectiveUsageLimits"`
	Clients Clients `json:"clients,omitempty"`
	// The policy ID used for controlling access to this solution, managed by resource `/policies/{policyId}`
	PolicyId string `json:"policyId"`
}
