/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).  The Bosch IoT Things HTTP API uses response status codes     (see [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6))     to indicate whether a specific request has been successfully completed, or not. However, the descriptions we provide additionally to the status code (e.g. in our API docs, or error codes like. \"solutions:transaction.count.exceeded\") might change without advance notice. These are not be considered as official API, and must therefore not be applied in your applications or tests.
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotthings
// OutboundMetrics Metrics of an outbound (e.g. a Target) resource
type OutboundMetrics struct {
	// Contains internally dispatched (e.g. a Ditto event) metric counts
	Dispatched TypedMetric `json:"dispatched"`
	// Contains the metric counts for messages which passed the filter (e.g. namespace or RQL filter for events)
	Filtered TypedMetric `json:"filtered"`
	// Contains mapped (payload mapping) messages metric counts
	Mapped TypedMetric `json:"mapped"`
	// Contains dropped (in the payload mapping) messages metric counts
	Dropped TypedMetric `json:"dropped"`
	// Contains published messages metric counts meaning those messages were published to the external source
	Published TypedMetric `json:"published"`
}
