/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).  The Bosch IoT Things HTTP API uses response status codes     (see [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6))     to indicate whether a specific request has been successfully completed, or not. However, the descriptions we provide additionally to the status code (e.g. in our API docs, or error codes like. \"solutions:transaction.count.exceeded\") might change without advance notice. These are not be considered as official API, and must therefore not be applied in your applications or tests.
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotthings
// Target A publish target served by this connection
type Target struct {
	// The target address where events, commands and messages are published to. The following placeholders are allowed within the target address:  * Thing ID: `{{ thing:id }}`  * Thing Namespace: `{{ thing:namespace }}`  * Thing Name: `{{ thing:name }}` (the part of the ID without the namespace)
	Address string `json:"address,omitempty"`
	// The topics to which this target is registered for
	Topics []string `json:"topics,omitempty"`
	// The authorization context defines all authorization subjects associated for this target
	AuthorizationContext []string `json:"authorizationContext,omitempty"`
	// A list of payload mappings that are applied to messages sent via this target. If no payload mapping is specified the standard Ditto mapping is used as default.
	PayloadMapping []string `json:"payloadMapping,omitempty"`
}
