/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).  The Bosch IoT Things HTTP API uses response status codes     (see [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6))     to indicate whether a specific request has been successfully completed, or not. However, the descriptions we provide additionally to the status code (e.g. in our API docs, or error codes like. \"solutions:transaction.count.exceeded\") might change without advance notice. These are not be considered as official API, and must therefore not be applied in your applications or tests.
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotthings
// ConnectionStatus Status of a connection and its resources
type ConnectionStatus struct {
	// The connection ID
	ConnectionId string `json:"connectionId"`
	// The desired/target status of the connection
	ConnectionStatus ConnectivityStatus `json:"connectionStatus"`
	// The current/actual status of the connection
	LiveStatus ConnectivityStatus `json:"liveStatus"`
	// The timestamp since when the connection is connected
	ConnectedSince string `json:"connectedSince"`
	// The client states of the of the connection
	ClientStatus []ResourceStatus `json:"clientStatus"`
	// The states of the sources the of the connection
	SourceStatus []ResourceStatus `json:"sourceStatus"`
	// The states of the targets the of the connection
	TargetStatus []ResourceStatus `json:"targetStatus"`
}
