/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).  The Bosch IoT Things HTTP API uses response status codes     (see [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6))     to indicate whether a specific request has been successfully completed, or not. However, the descriptions we provide additionally to the status code (e.g. in our API docs, or error codes like. \"solutions:transaction.count.exceeded\") might change without advance notice. These are not be considered as official API, and must therefore not be applied in your applications or tests.
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotthings
// SingleMetric Contains a single metric consisting of several time intervals and counter values for those intervals including the last message date.
type SingleMetric struct {
	// The counter containing how many messages were processed in the last minute
	PT1M int32 `json:"PT1M"`
	// The counter containing how many messages were processed in the last hour
	PT1H int32 `json:"PT1H"`
	// The counter containing how many messages were processed in the last 24 hours / last day
	PT24H int32 `json:"PT24H"`
	// The timestamp when the last message was processed
	LastMessageAt string `json:"lastMessageAt"`
}
